services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'fiveup'
      MYSQL_USER: 'Wuyu_Developer'
      MYSQL_PASSWORD: 'D3G@qrukHR5S'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  redis:
    image: redis:7.0
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  backend:
    build:
      context: ./wuyu-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '9080:9080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fiveup?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: Wuyu_Developer
      SPRING_DATASOURCE_PASSWORD: D3G@qrukHR5S
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./wuyu-server/src/main/resources/application.yml:/app/application.yml:Z  # 挂载 application.yml 文件

  frontend:
    build:
      context: ./wuyu-front
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./wuyu-front/nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载自定义配置

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
