server:
  port: 9085 # master分支端口，合并到master注意别改这个
spring:
  application:
    name: fiveup-core
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max-latest
      embedding:
        options:
          model: text-embedding-v3 # 向量模型名称
          dimensions: 1024 # 向量维度（就是将文本划分为1024维空间中的向量）
  jackson:
    default-property-inclusion: non_null # springboot默认解析对象为json对象时属性值为null时不予显示此属性

  datasource:
    url: jdbc:mysql://49.51.69.99:6603/fiveup?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: Wuyu_Developer
    password: D3G@qrukHR5S
    driver: com.mysql.jdbc.Driver
    # 连接池配置
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  servlet:
    multipart:
      max-file-size: 128MB #上传文件总大值
      max-request-size: 10MB  #单个文件的最大值


mybatis-plus:
  typeAliasesPackage: com.fiveup.core.**.**.domain
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true # 开启驼峰原则，将数据库带下划线的字段自动转为驼峰原则的命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis-plus配置控制台打印完整带参数SQL语句
